added ability to terminate based on ec2 tags.
1. upgraded to jcloud 2.0.0 from 1.9.0 to remove the following noClassDefFoundError when attempting to do POST HTTP networklatency chaos. 
	java.lang.NoClassDefFoundError: com/google/inject/internal/util/$Preconditions

2. forced com.google.inject.extensions to be version 4.0 to remove the 2nd NoClassDefFoundError when attempting to do POST HTTP networklatency chaos.
	java.lang.NoClassDefFoundError: com/google/inject/internal/util/$Maps
	
3. BasicInstance class now holds a new Instance type and not just a string. This Instance type will hold more detailed meta data of the instances, specifically the associated ec2 tags.

4. Here is a sample of the ec2 tags that are included in the JSON. Only ec2 instances that have all the matching key=value pairs will be considered for termination. Amongst these, 1 ec2 server will be randomly terminated.

{ "eventType":"CHAOS_TERMINATION", "groupType":"ASG", "groupName":"SimianMonkeyASG", "chaosType":"ShutdownInstance",
	"tags" : [
			{"key"  : "app-host-type", "value" : "reports"},
			{"key"  : "app-category", "value" : "reportServer"}			
		     ]
}

5. Unit tests were updated.